language: go
go:
  - 1.10.x
  - 1.11.x
sudo: false
install:
  - go get -v github.com/golang/dep/cmd/dep
  - dep ensure
  - go install ./hcAutonomyd/... ./hcAutonomywww/...
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh
